############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Calendar"
url = "calendar/"
weight = 2

# [[main]]
# name = "Partners"
# url = "partners/"
# weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu
[[footer]]
name = "Home"
url = ""
weight = 2

[[footer]]
name = "Calendar"
url = "calendar/"
weight = 3

# [[footer]]
# name = "Partners"
# url = "partners/"
# weight = 4

[[footer]]
name = "Blog"
url = "blog/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 6
